services:
  db:
    image: mysql
    restart: always
    command: --secure-file-priv=""
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      #- ./storage:/var/lib/mysql (I had issues with this Kavin did not I will leave commented out)
      - ./data/:/home/data
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOSTS: db

  #webserver:
